//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferreteria2.webservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices/", ConfigurationName="webservice.EquipoUsuarioWS")]
    public interface EquipoUsuarioWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/AgregarEquipoUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/AgregarEquipoUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ferreteria2.webservice.AgregarEquipoUsuarioResponse AgregarEquipoUsuario(Ferreteria2.webservice.AgregarEquipoUsuarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/EliminarEquipoUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/EliminarEquipoUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ferreteria2.webservice.EliminarEquipoUsuarioResponse EliminarEquipoUsuario(Ferreteria2.webservice.EliminarEquipoUsuarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/SeleccionarEquipoUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/SeleccionarEquipoUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ferreteria2.webservice.SeleccionarEquipoUsuarioResponse SeleccionarEquipoUsuario(Ferreteria2.webservice.SeleccionarEquipoUsuarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/ObtenerEquiposDeUsuarioRequest", ReplyAction="http://webservices/EquipoUsuarioWS/ObtenerEquiposDeUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ferreteria2.webservice.ObtenerEquiposDeUsuarioResponse ObtenerEquiposDeUsuario(Ferreteria2.webservice.ObtenerEquiposDeUsuarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices/EquipoUsuarioWS/ObtenerUsuariosDeEquipoRequest", ReplyAction="http://webservices/EquipoUsuarioWS/ObtenerUsuariosDeEquipoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ferreteria2.webservice.ObtenerUsuariosDeEquipoResponse ObtenerUsuariosDeEquipo(Ferreteria2.webservice.ObtenerUsuariosDeEquipoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarEquipoUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarEquipoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEquipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public AgregarEquipoUsuarioRequest() {
        }
        
        public AgregarEquipoUsuarioRequest(int idEquipo, int idUsuario) {
            this.idEquipo = idEquipo;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AgregarEquipoUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class AgregarEquipoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public AgregarEquipoUsuarioResponse() {
        }
        
        public AgregarEquipoUsuarioResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarEquipoUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarEquipoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EliminarEquipoUsuarioRequest() {
        }
        
        public EliminarEquipoUsuarioRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarEquipoUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class EliminarEquipoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public EliminarEquipoUsuarioResponse() {
        }
        
        public EliminarEquipoUsuarioResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class equipoUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int idEquipoField;
        
        private int idUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idEquipo {
            get {
                return this.idEquipoField;
            }
            set {
                this.idEquipoField = value;
                this.RaisePropertyChanged("idEquipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string avatarField;
        
        private string emailField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string avatar {
            get {
                return this.avatarField;
            }
            set {
                this.avatarField = value;
                this.RaisePropertyChanged("avatar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices/")]
    public partial class equipo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarEquipoUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarEquipoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public SeleccionarEquipoUsuarioRequest() {
        }
        
        public SeleccionarEquipoUsuarioRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SeleccionarEquipoUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class SeleccionarEquipoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Ferreteria2.webservice.equipoUsuario @return;
        
        public SeleccionarEquipoUsuarioResponse() {
        }
        
        public SeleccionarEquipoUsuarioResponse(Ferreteria2.webservice.equipoUsuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerEquiposDeUsuario", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerEquiposDeUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public ObtenerEquiposDeUsuarioRequest() {
        }
        
        public ObtenerEquiposDeUsuarioRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerEquiposDeUsuarioResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerEquiposDeUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Ferreteria2.webservice.equipo[] @return;
        
        public ObtenerEquiposDeUsuarioResponse() {
        }
        
        public ObtenerEquiposDeUsuarioResponse(Ferreteria2.webservice.equipo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuariosDeEquipo", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerUsuariosDeEquipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEquipo;
        
        public ObtenerUsuariosDeEquipoRequest() {
        }
        
        public ObtenerUsuariosDeEquipoRequest(int idEquipo) {
            this.idEquipo = idEquipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUsuariosDeEquipoResponse", WrapperNamespace="http://webservices/", IsWrapped=true)]
    public partial class ObtenerUsuariosDeEquipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Ferreteria2.webservice.usuario[] @return;
        
        public ObtenerUsuariosDeEquipoResponse() {
        }
        
        public ObtenerUsuariosDeEquipoResponse(Ferreteria2.webservice.usuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EquipoUsuarioWSChannel : Ferreteria2.webservice.EquipoUsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EquipoUsuarioWSClient : System.ServiceModel.ClientBase<Ferreteria2.webservice.EquipoUsuarioWS>, Ferreteria2.webservice.EquipoUsuarioWS {
        
        public EquipoUsuarioWSClient() {
        }
        
        public EquipoUsuarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EquipoUsuarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquipoUsuarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquipoUsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ferreteria2.webservice.AgregarEquipoUsuarioResponse Ferreteria2.webservice.EquipoUsuarioWS.AgregarEquipoUsuario(Ferreteria2.webservice.AgregarEquipoUsuarioRequest request) {
            return base.Channel.AgregarEquipoUsuario(request);
        }
        
        public bool AgregarEquipoUsuario(int idEquipo, int idUsuario) {
            Ferreteria2.webservice.AgregarEquipoUsuarioRequest inValue = new Ferreteria2.webservice.AgregarEquipoUsuarioRequest();
            inValue.idEquipo = idEquipo;
            inValue.idUsuario = idUsuario;
            Ferreteria2.webservice.AgregarEquipoUsuarioResponse retVal = ((Ferreteria2.webservice.EquipoUsuarioWS)(this)).AgregarEquipoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ferreteria2.webservice.EliminarEquipoUsuarioResponse Ferreteria2.webservice.EquipoUsuarioWS.EliminarEquipoUsuario(Ferreteria2.webservice.EliminarEquipoUsuarioRequest request) {
            return base.Channel.EliminarEquipoUsuario(request);
        }
        
        public bool EliminarEquipoUsuario(int id) {
            Ferreteria2.webservice.EliminarEquipoUsuarioRequest inValue = new Ferreteria2.webservice.EliminarEquipoUsuarioRequest();
            inValue.id = id;
            Ferreteria2.webservice.EliminarEquipoUsuarioResponse retVal = ((Ferreteria2.webservice.EquipoUsuarioWS)(this)).EliminarEquipoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ferreteria2.webservice.SeleccionarEquipoUsuarioResponse Ferreteria2.webservice.EquipoUsuarioWS.SeleccionarEquipoUsuario(Ferreteria2.webservice.SeleccionarEquipoUsuarioRequest request) {
            return base.Channel.SeleccionarEquipoUsuario(request);
        }
        
        public Ferreteria2.webservice.equipoUsuario SeleccionarEquipoUsuario(int id) {
            Ferreteria2.webservice.SeleccionarEquipoUsuarioRequest inValue = new Ferreteria2.webservice.SeleccionarEquipoUsuarioRequest();
            inValue.id = id;
            Ferreteria2.webservice.SeleccionarEquipoUsuarioResponse retVal = ((Ferreteria2.webservice.EquipoUsuarioWS)(this)).SeleccionarEquipoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ferreteria2.webservice.ObtenerEquiposDeUsuarioResponse Ferreteria2.webservice.EquipoUsuarioWS.ObtenerEquiposDeUsuario(Ferreteria2.webservice.ObtenerEquiposDeUsuarioRequest request) {
            return base.Channel.ObtenerEquiposDeUsuario(request);
        }
        
        public Ferreteria2.webservice.equipo[] ObtenerEquiposDeUsuario(int idUsuario) {
            Ferreteria2.webservice.ObtenerEquiposDeUsuarioRequest inValue = new Ferreteria2.webservice.ObtenerEquiposDeUsuarioRequest();
            inValue.idUsuario = idUsuario;
            Ferreteria2.webservice.ObtenerEquiposDeUsuarioResponse retVal = ((Ferreteria2.webservice.EquipoUsuarioWS)(this)).ObtenerEquiposDeUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ferreteria2.webservice.ObtenerUsuariosDeEquipoResponse Ferreteria2.webservice.EquipoUsuarioWS.ObtenerUsuariosDeEquipo(Ferreteria2.webservice.ObtenerUsuariosDeEquipoRequest request) {
            return base.Channel.ObtenerUsuariosDeEquipo(request);
        }
        
        public Ferreteria2.webservice.usuario[] ObtenerUsuariosDeEquipo(int idEquipo) {
            Ferreteria2.webservice.ObtenerUsuariosDeEquipoRequest inValue = new Ferreteria2.webservice.ObtenerUsuariosDeEquipoRequest();
            inValue.idEquipo = idEquipo;
            Ferreteria2.webservice.ObtenerUsuariosDeEquipoResponse retVal = ((Ferreteria2.webservice.EquipoUsuarioWS)(this)).ObtenerUsuariosDeEquipo(inValue);
            return retVal.@return;
        }
    }
}
